# Set the hostname for the Pi
# Depends on:
#   vars:
#       hostname: "test-pi-nes"
#

# Set the hostname
- name: Set the hostname
  become: yes
  command: hostnamectl set-hostname "{{ hostname }}"

- name: change Hosts
  become: yes
  lineinfile:
    path: /etc/hosts
    regexp: 'raspberrypi$'
    line: "127.0.0.1 {{ hostname }}"
    owner: root
    group: root
    mode: '0644'
