# ansible-playbook -i ~/ansible/hosts playbooks/new-default.yml
---
- name: Check if host is online
  hosts: addans
  gather_facts: yes
  vars:
    wifi_country: "AU"
    locale: "en_AU.UTF-8"
    keyboard: "pc104"
    keyboard_layout: "us"
    timezone: Australia/Sydney
    locale_options:
      # Disable Default (GB) Locale
      - regexp: "^#?en_GB.UTF-8 UTF-8"
        line: "# en_GB.UTF-8 UTF-8"
      # Enable AU Locale
      - regexp: "^#?en_AU.UTF-8 UTF-8"
        line: "en_AU.UTF-8 UTF-8"

  tasks:

    - name: Debug the hostname
      debug:
        var: hostname

      # Expand the filesystem
    - include: ../tasks/expand-filesystem.yml
      tags: setup

      # Set Internationalization Options
    - include: ../tasks/internationalization.yml
      tags: setup

    - name: Create SSH folder
      file: path=~/.ssh state=directory

    - name: Set up SSH Key from a template
      template:
         src: ../../.ssh/authorized_keys 
         dest: ~/.ssh/authorized_keys
         force: no

    - name: run 'dpkg --configure -a'
      become: yes
      command: dpkg --configure -a

      # Run apt-get update and apt-get upgrade
    - include: ../tasks/update.yml
      tags: update

      # Set the hostname
    - include: ../tasks/hostname.yml
      tags: setup

  handlers:

    - include: ../handlers/rebootnewhost.yml
      tags: system

    - include: ../handlers/tzdata.yml
      tags: system
