# ansible-playbook -v -i ~/ansible/hosts /playbooks/setup-hostapd.yml
---
- name:               Configure WIFI Hotspot for RaspberryPi 3
  hosts:              hostapd
  become:             true
  gather_facts:       yes
  vars:
    wpa_passphrase:   NPRraspi
    interface:        wlan0
    ssid:             NPRSlave
    ip_server:        192.168.4.1
    netmask:          255.255.255.0
    network:          192.168.4.0
    gateway:          192.168.4.1
    broadcast:        192.168.4.255
    ip_dhcp_low:      192.168.4.20
    ip_dhcp_high:     192.168.4.30

    sysctl_options:
      # Disable HDMI on startup (for power savings).
      - regexp:       "^#?net.ipv4.ip_forward=1"
        line:         "net.ipv4.ip_forward=1"

    hostapd_options:
      - regexp:       "^#?DAEMON_CONF"
        line:         'DAEMON_CONF="/etc/hostapd/hostapd.conf"'

  tasks:

     - name:          Install dependancies from apt
       apt:
         pkg:
          - git-core
          - dnsmasq
          - hostapd
          - minicom
          - lsof
         state:       present

     - name:          Remove bloatware from apt
       apt:
         pkg:
             - wolfram-engine
             - libreoffice*
         state:       absent

# oinly needed fo bridging
 #    - name:          Configure options in /etc/sysctl.conf
  #     become:       yes
 #      lineinfile:
 #        dest:        /etc/sysctl.conf
 #        regexp:      "{{ item.regexp }}"
 #        line:        "{{ item.line }}"
 #        insertafter: EOF
 #        state:       present
 #      with_items:    "{{ sysctl_options }}"
 #      notify:
 #         - reboot


     - name:          dnsmasq.conf
       template:
         src:         hostapd.dnsmasq.conf.nat
         dest:        /etc/dnsmasq.conf
         backup:      true

     - name:          hostapd.conf
       template:
         src:         hostapd.hostapd.conf.nat
         dest:        /etc/hostapd/hostapd.conf
         backup:      true

     - name:          hostapd
       lineinfile:
         dest:        /etc/default/hostapd
         regexp:      "{{ item.regexp }}"
         line:        "{{ item.line }}"
         insertafter: EOF
         state:       present
       with_items:    "{{ hostapd_options }}"


#       template:
#         src:         hostapd.hostapd.nat
#         dest:        /etc/default/hostapd
#         backup:      true

#     - name:          rc.local
#       template:
#         src:         hostapd.rc.local.nat
#         dest:        /etc/rc.local
#         backup:      true

#don't configure interfaces wit autohotspot
#     - name:          interfaces
#       template:
#         src:         hostapd.interfaces.nat
#         dest:        /etc/network/interfaces
#         backup:      true

     - name:          dhcpcd
       blockinfile:
         path:        /etc/dhcpcd.conf
         block:
           nohook wpa_suplicant

     - name:          autohotspot service create
       copy:
         src:         files/hostapd.autohotspot.service
         dest:        /etc/systemd/system/autohotspot.service
         backup:      true

     - name: just force systemd reload
       systemd:
         daemon_reload: yes

     - name:              create autohotspot script
       template:
         src:             hostapd.autohotspot
         dest:            /usr/bin/autohotspot
         mode:           0755
#    - name:          networking service
#      service:       name=networking enabled=yes state=restarted

     - name:          dnsmasq service
       systemd:
         name:        dnsmasq
         enabled:     no
         state:       stopped

     - name:          hostapd service
       systemd:
         name:        hostapd
         enabled:     no
         state:       stopped
         masked:      no

     - name:          autohotspot service
       systemd:
         name:        autohotspot
         enabled:     yes
         state:       started
#    - name:          restart machine
#      shell:         sleep 2 && shutdown -r now
#      async:         1
#      poll:          0
#      ignore_errors: true


  handlers:

      - include:      ../handlers/reboot.yml
        tags:         system
